<input type="hidden" value="0" name="pageIndex" id="pageIndex"/>   
    <div class="smallHeader">
      <div class="smallHeaderText"> <span class="title">An error occurred</span> <br/>
        <span class="whiteText"><?= $this->message ?></span> </div>

    </div>
    <!--content-->
    <div id="content">
      <div id="contentContainer">
        <div class="content_text"> 
        
        
		  <? if ('development' == APPLICATION_ENV): ?>
		
		  <span class="greyTitle">Exception information:</span>
		  <p class="text">
		      <b>Message:</b> <?= $this->exception->getMessage() ?>
		  </p>
		
		  <span class="greyTitle">Stack trace:</span>
		  <pre><?= $this->exception->getTraceAsString() ?>
		  </pre>
		
		  <span class="greyTitle">Request Parameters:</span>
		  <pre><? var_dump($this->request->getParams()) ?>
		  </pre>
		  <? endif ?>        


        </div>
      </div>
    </div>
