<table cellpadding="0" cellspacing="0" class="<?php echo ($this->tableclass) ? $this->tableclass : 'tablesorter'; ?>" id="<?php echo ($this->tableid) ? $this->tableid : 'moji_proj_team'; ?>">
	<thead>
		<tr>
			<th>Who</th>	
			<th>Email</th>
			<th>Title</th>
			<th>Added</th>
			<?php if($this->enable_actions):?>
			<th></th>
			<?php endif; ?>	
		</tr>
	</thead>

	<tbody>
		<?php 
		$i = 0;
		foreach($this->proj_team as $user)
		{
			$user_data = array(
							'id' => $user['user_id'], 
							'first_name' => $user['first_name'], 
							'last_name' => $user['last_name']
			);			
		?>
		<tr>
			<td><?php echo $this->MakeLink('user', $user_data); ?></td>
			<td><?php echo $user['email']; ?></td>
			<td><?php echo ($user['job_title'] == '' ? 'N/A' : $user['job_title']); ?></td>
			<td><?php echo $this->RelativeDate($user['created_date']); ?></td>	
		</tr>
		<?php 
		}
		?>
	</tbody>
</table>