<style>
#loading
{
	display:none;
}
</style>
<form action="<?php echo $this->escape($this->form->getAction()); ?>" id="timers_form"
method="<?php echo $this->escape($this->form->getMethod()) ?>" enctype="<?php echo $this->escape($this->form->getEnctype()); ?>">
	
	<?php if($this->company): ?>
	<p>
		<label for="company_id" id="companies">Company</label>
		<a href="<?php echo $this->url(array('module' => 'pm','controller'=>'companies','action'=>'view', 'id' => $this->company['id']), null, TRUE); ?>"><?php echo $this->company['name']; ?></a>
		<input type="hidden" name="company" value="<?php echo $this->company['id']; ?>" />
	</p>
	<?php endif; ?>
	
	<?php if($this->project): ?>
	<p>
		<label for="project_id">Project</label>
		<a href="<?php echo $this->url(array('module' => 'pm','controller'=>'projects','action'=>'view', 'id' => $this->project['id']), null, TRUE); ?>"><?php echo $this->project['name']; ?></a>
		<input type="hidden" name="project" value="<?php echo $this->project['id']; ?>" />
	</p>
	<?php endif; ?>
	
	<?php if($this->task): ?>
	<p>
		<label for="task_id">Task</label>
		<a href="<?php echo $this->url(array('module' => 'pm','controller'=>'tasks','action'=>'view', 'id' => $this->task['id']), null, TRUE); ?>"><?php echo $this->task['name']; ?></a>
		<input type="hidden" name="task" value="<?php echo $this->task['id']; ?>" />
	</p>
	<?php endif; ?>
	<p>
		<label for="billable">Billable: <?php echo $this->form->billable; ?></label>
	</p>	
	<p>
		<label for="hours">Hours</label>
		<?php echo $this->timer_data['time_running']['hours']; ?>
	</p>	
	<p>
		<label for="date">Date</label>
		<?php echo $this->RelativeDate($this->timer_data['date']); ?>
	</p>		
	<p>
		<label for="description">Description</label>
		<?php echo $this->form->description; ?>
	</p>
	
	<p>
		<input type="submit" class="submit" value="Stop Timer" />
	</p>		
				
</form>	

<div id="loading"><img src="/images/loading.gif" /></div>
<script type="text/javascript">
jQuery(document).ready(function($){
		
	$("#timers_form").validate({
		rules: {
			description: "required"
		},
		messages: {
			description: "Please enter a description"			
		}
	});	
	$('input:checkbox').checkbox();
});
</script>	