
<form action="<?php echo $this->escape($this->form->getAction()); ?>" method="<?php echo $this->escape($this->form->getMethod()) ?>" id="task_form">
<input type="hidden" name="start_date_default" id="start_date_default" value="<?php echo date('Y-m-d'); ?>" />
<input type="hidden" name="end_date_default" id="end_date_default" value="<?php echo date('Y-m-d'); ?>" />
<?php 
if($this->id > 0)
{
	echo '<input type="hidden" value="'.$this->id.'" name="id" />';
} elseif($this->project_data) {
	echo '<input type="hidden" value="'.$this->project_data['id'].'" name="project_id" />';
}
?>
<div id="form_tabs">
	<ul>

		<li><a href="#general">General</a></li>
		<li><a href="#details">Details</a></li>
	</ul>
	<div id="general">
	
		<p>
			<label for="name">Name</label>
			<?php echo $this->form->name; ?>
		</p>
		
		<p>
			<label for="project_id">Project</label>
			<a href="<?php echo $this->url(array('module' => 'pm','controller' => 'projects','action'=>'view', 'id' => $this->project_data['id']), null, TRUE); ?>"><?php echo $this->project_data['name']; ?></a>
			
		</p>
		
		<p>
			<label for="assigned_to">Assigned To</label>
			<?php echo $this->form->assigned_to; ?> <a href="<?php echo $this->url(array('module' => 'pm','controller' => 'docs','action'=>'tasks', 'page' => 'assigned_to'), null, TRUE); ?>" rel="facebox"><?php echo $this->InteractIcon('help', 'About Task Assigned To');?></a>
		</p>
		
		<p style="display: none" id="assignment_comment">
			<label for="assign_comment">Assignment Comment</label>
			<?php echo $this->form->assign_comment; ?>
		</p>				
		
		<p>
			<label for="status">Status</label>
			<?php echo $this->form->status; ?> <a href="<?php echo $this->url(array('module' => 'pm','controller' => 'docs','action'=>'tasks', 'page' => 'status'), null, TRUE); ?>" rel="facebox"><?php echo $this->InteractIcon('help', 'About Task Status');?></a>
		</p>
		
		<p>
			<label for="priority">Priority</label>
			<?php echo $this->form->priority; ?>
		</p>
		
		<p>
			<label for="type">Type</label>
			<?php echo $this->form->type; ?> <a href="<?php echo $this->url(array('module' => 'pm','controller' => 'docs','action'=>'tasks', 'page' => 'type'), null, TRUE); ?>" rel="facebox"><?php echo $this->InteractIcon('help', 'About Task Types');?></a>
		</p>																	
		
		<p>
			<label for="description">Description</label>
			<?php echo $this->form->description; ?>
		</p>
		
		<p>
			<input type="submit" class="submit" value="Submit" />
		</p>				
	
	</div>
	
	<div id="details">
	
		<p>
			<label for="start_date">Start Date</label>
			<?php echo $this->form->start_date; ?> <?php echo $this->form->start_hour; ?> <?php echo $this->form->start_minute; ?> <a href="<?php echo $this->url(array('module' => 'pm','controller' => 'docs','action'=>'tasks', 'page' => 'start_date'), null, TRUE); ?>" rel="facebox"><?php echo $this->InteractIcon('help', 'About Task Start Date');?></a>
		</p>

		<p>
			<label for="end_date">End Date</label>
			<?php echo $this->form->end_date; ?> <?php echo $this->form->end_hour; ?> <?php echo $this->form->end_minute; ?> <a href="<?php echo $this->url(array('module' => 'pm','controller' => 'docs','action'=>'tasks', 'page' => 'end_date'), null, TRUE); ?>" rel="facebox"><?php echo $this->InteractIcon('help', 'About Task Stop Date');?></a>
		</p>
		
		<p>
			<label for="progress">Progress</label>
			<?php echo $this->form->progress; ?> % <a href="<?php echo $this->url(array('module' => 'pm','controller' => 'docs','action'=>'tasks', 'page' => 'progress'), null, TRUE); ?>" rel="facebox"><?php echo $this->InteractIcon('help', 'About Task Progress');?></a>
		</p>		
		
		<p>
			<label for="duration">Expected Duration</label>
			<?php echo $this->form->duration; ?> <?php echo $this->form->duration_type; ?> hours <a href="<?php echo $this->url(array('module' => 'pm','controller' => 'docs','action'=>'tasks', 'page' => 'duration'), null, TRUE); ?>" rel="facebox"><?php echo $this->InteractIcon('help', 'About Task Duration');?></a>
		</p>
		
		<p>
			<input type="submit" class="submit" value="Submit" />
		</p>				
	
	</div>

</div>
</form>	

<script type="text/javascript">
var def_assign = '<?php echo ($this->task_data['assigned_to'] ? $this->task_data['assigned_to'] : 0); ?>';
jQuery(document).ready(function($){
	$("#assigned_to").change(function(){
		//$("#assignment_comment").show();
		var new_assign = $("#assigned_to").val();
		if(new_assign == def_assign || new_assign == 0)
		{
			$("#assignment_comment").hide();
		}
		else
		{
			$("#assignment_comment").show();
		}
	});

	$("#task_form").validate({
		rules: {
			name: "required",
			description: "required"
		},
		messages: {
			name: "Please enter a task name",
			description: "Please enter a description"
		}
	});	
});
</script>
<?php echo $this->ConfirmPageUnload('#task_form')?>