<div class="content_headers" style="padding-top:0px;">
	<div class="admin_header">Remove Ip Address</div>	
</div>
<?php if(!$this->ajax_mode): ?>
<div class="back_link_content">
	<a href="<?php echo $this->url(array('module' => 'pm','controller'=>'ips','action'=>'view', 'id'=>$this->id), null, TRUE); ?>" title="Back to Ip">
		Back to Ip
	</a><div><?php echo $this->InteractIcon('left-arrow', 'Back to Ip');?></div>
</div>	
<br clear="all" />
<?php endif; ?>

<?php if($this->deny): ?>
<div class="fail png_bg">
You can't delete your Ip address while ip blocking is enabled.
</div>

<?php else: ?>
<div class="attention png_bg">
Are you sure you want to remove the Ip Address <?php echo $this->ip['ip_raw']?>? This can not be undone...
</div>
<p>
<form action="<?php echo $this->url(array('module' => 'pm','controller'=>'ips','action'=>'remove', 'id' => $this->id), null, TRUE); ?>" method="POST">
	<input type="submit" class="submit" value="Yes" name="confirm" /> <input type="submit" class="submit" value="No" name="fail"/>
</form>
</p>
<?php endif; ?>