<table cellpadding="0" cellspacing="0" class="tablesorter" id="file_revisions">
	<thead>
		<tr>
			<th>#</th>
			<th>Type</th>
			<th>Name</th>			
			<th>Uploaded By</th>
			<th>Uploaded</th>
			<th>Size</th>
			<th></th>
		</tr>
	</thead>

	<tbody>
		<?php 
		$i = 0;
		foreach($this->revisions as $revision)
		{
			$uploader_data = array(
							'id' => $revision['uploaded_by'], 
							'first_name' => $revision['uploader_first_name'], 
							'last_name' => $revision['uploader_last_name']
			);
		?>		
		<tr>
			<td><?php echo ($i+1); ?></td>
			<td><?php echo $this->FileTypeImage($revision['mime_type'])?></td>
			<td><?php echo $revision['file_name']; ?></td>
			<td><?php echo $this->MakeLink('user', $uploader_data);?></td>
			<td><?php echo $this->RelativeDate($revision['created_date']); ?></td>
			<td><?php echo $this->FileSize($revision['size']); ?></td>
			<td>
			<a href="<?php echo $this->url(array('module' => 'pm','controller'=>'files','action'=>'remove-revision', 'id' => $revision['id']), null, TRUE); ?>" title="Delete" rel="facebox"><?php echo $this->InteractIcon('cross', 'Delete');?></a>
			<a href="<?php echo $this->url(array('module' => 'pm','controller'=>'files','action'=>'download-revision', 'id' => $revision['id']), null, TRUE); ?>" title="Download"><?php echo $this->InteractIcon('save_disk', 'Download');?></a>
			<a href="<?php echo $this->url(array('module' => 'pm','controller'=>'files','action'=>'preview-revision', 'id' => $revision['id']), null, TRUE); ?>" title="Preview" rel="facebox"><?php echo $this->InteractIcon('preview', 'Preview');?></a>
			</td>
		</tr>
		<?php 
			$i++;
		}
		?>
	</tbody>
</table>