<form id="company_form" action="<?php echo $this->escape($this->form->getAction()); ?>" method="<?php echo $this->escape($this->form->getMethod()) ?>">
<?php 
	if($this->id > 0)
		echo '<input type="hidden" value="'.$this->id.'" name="id" />';
?>	
<div id="form_tabs">
	<ul>

		<li><a href="#general">General</a></li>
		<li><a href="#address">Address</a></li>
		<li><a href="#phone">Phone</a></li>
	</ul>
	<div id="general">

		<p>
			<label for="name">Name</label>
			<?php echo $this->form->name; ?>
		</p>

		<p>
			<label for="primary_url">Website</label>
			<?php echo $this->form->primary_url; ?>
		</p>
		
		<p>
			<label for="type">Type</label>
			<?php echo $this->form->type; ?> <a href="<?php echo $this->url(array('module' => 'pm','controller' => 'docs','action'=>'companies', 'page' => 'type'), null, TRUE); ?>" rel="facebox"><?php echo $this->InteractIcon('help', 'About Company Type');?></a> 
		</p>
		
		<p>
			<label for="description">Description</label>
			<?php echo $this->form->description; ?>
		</p>		
		
		<p>
			<input type="submit" class="submit" value="Submit" />
		</p>				
	</div>
	<div id="address">
		
		<p>
			<label for="address1">Address 1</label>
			<?php echo $this->form->address1; ?>
		</p>
		
		<p>
			<label for="address2">Address 2</label>
			<?php echo $this->form->address2; ?>
		</p>
		
		<p>
			<label for="city">City</label>
			<?php echo $this->form->city; ?>
		</p>
		
		<p>
			<label for="zip">Zip</label>
			<?php echo $this->form->zip; ?>
		</p>
		
		<p>
			<label for="state">State</label>
			<?php echo $this->form->state; ?>
		</p>
		
		<p>
			<input type="submit" class="submit" value="Submit" />
		</p>		
	
	</div>
	<div id="phone">
		<p>
			<label for="phone1">Phone</label>
			<?php echo $this->form->phone1; ?>
		</p>
			
		<p>
			<label for="phone2">Phone 2</label>
			<?php echo $this->form->phone2; ?>
		</p>
		
		<p>
			<label for="fax">Fax</label>
			<?php echo $this->form->fax; ?>
		</p>
		
		<p>
			<input type="submit" class="submit" value="Submit" />
		</p>			
	</div>
</div>	
</form>
<script type="text/javascript">
$.validator.setDefaults({
	//submitHandler: function() { alert("submitted!"); }
});

$().ready(function() {

	$("#company_form").validate({
		rules: {
			name: "required"
		},
		messages: {
			name: "Please enter a company name"
		}
	});

});

</script>



