<form id="user_form" action="<?php echo $this->escape($this->form->getAction()); ?>" method="<?php echo $this->escape($this->form->getMethod()) ?>">
<?php 
	if($this->id > 0)
		echo '<input type="hidden" value="'.$this->id.'" name="id" />';
?>	
<div id="form_tabs">
	<ul>

		<li><a href="#general">General</a></li>
		<li><a href="#phone">Phone</a></li>
		<li><a href="#im">IM</a></li>
		<?php if($this->CheckPermission('manage_users')):?>
		<li><a href="#roles">Roles</a></li>
		<?php endif; ?>
	</ul>
	<div id="general">
		
		<p>
			<label for="first_name">First Name</label>
			<?php echo $this->form->first_name; ?>
		</p>				
		
		<p>
			<label for="last_name">Last Name</label>
			<?php echo $this->form->last_name; ?>
		</p>			
		
		<p>
			<label for="email">Email</label>
			<?php echo $this->form->email; ?>
		</p>
		
		<?php if($this->addPassword): ?>
		<p>
			<label for="password">Password</label>
			<?php echo $this->form->password; ?>
		</p>
		
		<p>
			<label for="confirm_password">Confirm Password</label>
			<?php echo $this->form->confirm_password; ?>
		</p>
		<?php endif; ?>	
		
		<p>
			<label for="job_title">Title</label>
			<?php echo $this->form->job_title; ?>
		</p>
		
		<p>
			<label for="description">Description</label>
			<?php echo $this->form->description; ?>
		</p>		
		
		<p>
			<input type="submit" class="submit" value="Submit" />
		</p>				
	</div>
	<div id="phone">
		<p>
			<label for="phone_home">Home</label>
			<?php echo $this->form->phone_home; ?>
		</p>
			
		<p>
			<label for="phone2">Work</label>
			<?php echo $this->form->phone_work; ?>
		</p>
		
		<p>
			<label for="mobile">Mobile</label>
			<?php echo $this->form->phone_mobile; ?>
		</p>
		
		<p>
			<label for="fax">Fax</label>
			<?php echo $this->form->phone_fax; ?>
		</p>
		
		<p>
			<input type="submit" class="submit" value="Submit" />
		</p>			
	</div>
	<div id="im">
		<p>
			<label for="jabber">Jabber</label>
			<?php echo $this->form->jabber; ?>
		</p>
			
		<p>
			<label for="aol">AIM</label>
			<?php echo $this->form->aol; ?>
		</p>
		
		<p>
			<label for="yahoo">Yahoo!</label>
			<?php echo $this->form->yahoo; ?>
		</p>
		
		<p>
			<label for="google_talk">Google Talk</label>
			<?php echo $this->form->google_talk; ?>
		</p>
		
		<p>
			<label for="msn">MSN</label>
			<?php echo $this->form->msn; ?>
		</p>	
		<p>
			<label for="ichat">iChat</label>
			<?php echo $this->form->ichat; ?>
		</p>
		
		<p>
			<label for="skype">Skype</label>
			<?php echo $this->form->skype; ?>
		</p>						
		
		<p>
			<input type="submit" class="submit" value="Submit" />
		</p>			
	</div>	
	<?php if($this->CheckPermission('manage_users')):?>
	<div id="roles">
		
		<p class="user_role_boxes">
		<?php echo $this->form->user_roles; ?>		
		</p>
		
		<p>
			<input type="submit" class="submit" value="Submit" />
		</p>			
	</div>	
	<?php endif; ?>		
</div>	
</form>

<script type="text/javascript">
jQuery(document).ready(function($){
	$("#user_form").validate({
		rules: {
			first_name: "required",
			last_name: "required",
			email: {
				required: true,
				email: true
			},
			password: {
				required: true,
				minlength: 5
			},
			confirm_password: {
				required: true,
				equalTo: "#password",
				minlength: 5
			},
			user_roles: "required"
		},
		messages: {
			first_name: "Please enter a first name",
			last_name: "Please enter a last name",
			email: {
				required: "Please enter an email",
				email: "Please enter a valid email address"
			},
			password: {
				required: "Please enter a password",
				minlength: "Your password must be at least 5 characters long"
			},
			confirm_password: {
				required: "Please confirm your password",
				equalTo: "Please enter the same password as above",
				minlength: "Your password must be at least 5 characters long"
			},
			user_roles: "Please choose the roles for the user"
		}
	});	
	$.validator.setDefaults({
		submitHandler: function() { return confirm("submitted!"); }
	});	
});
</script>