<form id="password_form" action="<?php echo $this->escape($this->form->getAction()); ?>" method="<?php echo $this->escape($this->form->getMethod()) ?>">
		<p>
			<label for="old_password">Current Password</label>
			<?php echo $this->form->old_password; ?>
		</p>				
		
		<p>
			<label for="new_password">New Password</label>
			<?php echo $this->form->new_password; ?>
		</p>			
		
		<p>
			<label for="confirm_password">Confirm Password</label>
			<?php echo $this->form->confirm_password; ?>
		</p>
				
		
		<p>
			<input type="submit" class="submit" value="Submit" />
		</p>				

</form>

<script type="text/javascript">
jQuery(document).ready(function($){
	$("#password_form").validate({
		rules: {
			old_password: {
				required: true
			},
			new_password: {
				required: true,
				minlength: 5
			},
			confirm_password: {
				required: true,
				equalTo: "#new_password",
				minlength: 5
			}
		},
		messages: {
			old_password: {
				required: "Please enter your old password",
			},			
			new_password: {
				required: "Please enter a new password",
				minlength: "Your password must be at least 5 characters long"
			},
			confirm_password: {
				required: "Please confirm your new password",
				equalTo: "Please enter the same password as above",
				minlength: "Your password must be at least 5 characters long"
			}
					
		}
	});	
});
</script>