<div class="content_headers" style="padding:0px;">
	<div class="user_header">Account Settings</div>	
</div>
<dl>
	<dt><a href="<?php echo $this->url(array('module' => 'pm','controller' => 'users','action'=>'edit'), null, TRUE); ?>">Modify Account Info</a></dt>
	<dd>Modify the information about your account.</dd>
	<dt><a href="<?php echo $this->url(array('module' => 'pm','controller' => 'settings','action'=>'password'), null, TRUE); ?>">Change Password</a></dt>
	<dd>Change the password you use to login with.</dd>
	<dt><a href="<?php echo $this->url(array('module' => 'pm','controller' => 'settings','action'=>'prefs'), null, TRUE); ?>">Preferences</a></dt>
	<dd>Update how MojiTRAC works just for you.</dd>	
</dl>