<div class="content_headers" style="padding-top:0px;">
	<div class="contact_header">Add Contact</div>
</div>
<div class="back_link_content">
	<a href="<?php echo $this->url(array('module' => 'pm','controller'=>'companies','action'=>'view', 'id'=>$this->company_data['id']), null, TRUE); ?>" title="Back to <?php echo $this->company_data['name']; ?>">
		Back to <?php echo $this->company_data['name']; ?>	
	</a><div><?php echo $this->InteractIcon('left-arrow', 'Back to '.$this->company_data['name']);?></div>
</div>
<br clear="all" />
<?php 
$options = array('form' => $this->form, 'addAction' => $this->addAction, 'company_data' => $this->company_data);
echo $this->partial('contacts/partials/form.phtml', $options);
?>