<div class="content_headers" style="padding-top:0px;">

	<div class="user_header">View User: <?php echo $this->user['first_name'].' '.$this->user['last_name'];?></div>
		<div class="actions">
			<a href="<?php echo $this->url('docs', array('module' => 'pm','controller' => 'docs','action'=>'users', 'page' => 'view')); ?>" rel="facebox" title="Add Project">
				<?php echo $this->InteractIcon('help', 'About Users');?>
				<div class="action_text">Help</div>
			</a>
		</div>		
		
		<?php if($this->user['email']): ?>
		<div class="actions">
			<a href="mailto:<?php echo $this->user['email']; ?>" title="Email">
				<?php echo $this->InteractIcon('email', 'Email User');?>
				<div class="action_text">Email</div>
			</a>
		</div>				
		<?php endif; ?>
		<?php if($this->CheckPermission('manage_users')):?>
		<div class="actions">
			<a href="<?php echo $this->url('users/remove', array('user_id' => $this->user['id'])); ?>" title="Delete">
				<?php echo $this->InteractIcon('cross', 'Remove User');?>
				<div class="action_text">Delete</div>
			</a>
		</div>	
		<?php endif; ?>	
		<?php if($this->CheckPermission('manage_users') || $this->id == $this->identity):?>
		<div class="actions">
			<a href="<?php echo $this->url('users/edit', array('user_id' => $this->user['id'])); ?>" title="Edit">
				<?php echo $this->InteractIcon('pencil', 'Edit User');?>
				<div class="action_text">Edit</div>
			</a>
		</div>
		<?php endif; ?>		
</div>

<div class="item_details">
    <div class="items">
    	<p>
    		<span class="bold">Email:</span> <a href="mailto:<?php echo $this->user['email']; ?>"><?php echo $this->Truncate($this->user['email'], '25'); ?></a><br />
			<?php if($this->user['job_title']):?>
			<span class="bold">Title:</span> <?php echo $this->user['job_title']; ?><br />
			<?php endif; ?> 
			<span class="bold">Last Modified:</span> <?php echo $this->RelativeDate($this->user['last_modified']); ?><br />
			<span class="bold">Created Date:</span> <?php echo $this->RelativeDate($this->user['created_date']); ?><br />
    	</p>
    </div>
    <?php if($this->user['phone_home'] || $this->user['phone_mobile'] || $this->user['phone_work'] || $this->user['phone_fax']):?>
    <div class="items" style="padding-left:10px;">
    	<p>
			<?php if($this->user['phone_home']):?>
				<span class="bold">Home Phone:</span> <?php echo $this->user['phone_home']; ?><br />
			<?php endif; ?>
			<?php if($this->user['phone_mobile']):?>
				<span class="bold">Mobile Phone:</span> <?php echo $this->user['phone_mobile']; ?><br />
			<?php endif; ?>			
			<?php if($this->user['phone_work']):?>
				<span class="bold">Work Phone:</span> <?php echo $this->user['phone_work']; ?><br />
			<?php endif; ?>
			<?php if($this->user['phone_fax']):?>
				<span class="bold">Fax:</span> <?php echo $this->user['phone_fax']; ?>  
			<?php endif; ?>  	
    	</p>
    </div>
    <?php endif; ?> 
    <?php if($this->user['jabber'] || $this->user['aol'] || $this->user['yahoo'] || $this->user['google_talk'] || $this->user['msn'] || $this->user['ichat'] || $this->user['skype']):?>
    <div class="items" style="padding-left:10px;">
    	<p>
    		<?php if($this->user['jabber']):?>
				<span class="bold">Jabber:</span> <?php echo $this->user['jabber']; ?><br />
			<?php endif; ?> 
			<?php if($this->user['aol']):?>
				<span class="bold">AIM:</span> <?php echo $this->user['aol']; ?><br />
			<?php endif; ?> 
			<?php if($this->user['yahoo']):?>
				<span class="bold">Yahoo!:</span> <?php echo $this->user['yahoo']; ?><br />
			<?php endif; ?> 
			<?php if($this->user['google_talk']):?>
				<span class="bold">Google Talk:</span> <?php echo $this->user['google_talk']; ?><br />
			<?php endif; ?> 
			<?php if($this->user['msn']):?>
				<span class="bold">MSN:</span> <?php echo $this->user['msn']; ?><br />
			<?php endif; ?> 
			
			<?php if($this->user['skype']):?>
				<span class="bold">Skype:</span> <?php echo $this->user['skype']; ?><br />
			<?php endif; ?> 
			
			<?php if($this->user['ichat']):?>
				<span class="bold">iChat:</span> <?php echo $this->user['ichat']; ?><br />
			<?php endif; ?> 						
    	</p>
    </div> 
    <?php endif; ?>   
    <?php if($this->CheckPermission('view_time')): ?>
    <div class="items" style="padding-left:10px;">
		<?php 
			$options = array('hours' => $this->hours, 'type' => 'user', 'id' => $this->id);
			echo $this->partial('pm/times/partials/hour_status', $options); 		
		?>
    </div>
    <?php endif; ?>
</div>

<br clear="all" />

<?php if($this->user['description'] != ''): ?>
<h2>Description:</h2>
<p><?php echo nl2br($this->user['description']); ?></p>
<?php endif; ?>

<?php 
if($this->roles):
?>
<div class="content_headers">
	<div class="user_role_header">User Roles</div>	
	<div class="actions">
		<a href="<?php echo $this->url('pm', array('module' => 'pm','controller' => 'docs','action'=>'users', 'page' => 'roles'), null, TRUE); ?>" rel="facebox" title="Add Project">
			<?php echo $this->InteractIcon('help', 'About User Roles');?>
			<div class="action_text">Help</div>
		</a>
	</div>			
</div>
<?php 
	$options = array('roles' => $this->roles);
	echo $this->partial('pm/roles/partials/roles', $options); 
endif; ?>

<div class="content_headers">
	<div class="project_header">Projects</div>	
	<div class="actions">
		<a href="<?php echo $this->url('pm', array('module' => 'pm','controller' => 'docs','action'=>'users', 'page' => 'projects'), null, TRUE); ?>" rel="facebox" title="Add Project">
			<?php echo $this->InteractIcon('help', 'About User Projects');?>
			<div class="action_text">Help</div>
		</a>
	</div>		
</div>
<?php 
if($this->projects):
	$options = array('projects' => $this->projects);
	echo $this->partial('pm/projects/partials/projects', $options); 
else: 
?>
<div class="information png_bg"><?php echo $this->user['first_name'].' '.$this->user['last_name'];?> isn't assigned to any projects yet.</div>
<?php endif; ?>


<?php 
if($this->tasks): 
?>
<div class="content_headers">
	<div class="task_header">Tasks</div>	
	<div class="actions">
		<a href="<?php echo $this->url('pm', array('module' => 'pm','controller' => 'docs','action'=>'users', 'page' => 'tasks'), null, TRUE); ?>" rel="facebox" title="Add Project">
			<?php echo $this->InteractIcon('help', 'About User Tasks');?>
			<div class="action_text">Help</div>
		</a>
	</div>		
</div>
<?php 
	$options = array('tasks' => $this->tasks, 'enable_due' => 'yes', 'enable_assigned' => 'yes', 'enable_completion' => 'yes');
	echo $this->partial('pm/tasks/partials/tasks', $options); 
endif; ?>

<?php 
if($this->files):
?>
<div class="content_headers">
	<div class="file_header">Files</div>	
	<div class="actions">
		<a href="<?php echo $this->url('pm', array('module' => 'pm','controller' => 'docs','action'=>'users', 'page' => 'files'), null, TRUE); ?>" rel="facebox" title="Add Project">
			<?php echo $this->InteractIcon('help', 'About User Files');?>
			<div class="action_text">Help</div>
		</a>
	</div>		
</div>
<?php 
	$options = array('files' => $this->files);
	echo $this->partial('pm/files/partials/files', $options); 
endif;
?>

<?php 
if($this->notes):
?>
<div class="content_headers">
	<div class="note_header">Notes</div>
	<div class="actions">
		<a href="<?php echo $this->url('pm', array('module' => 'pm','controller' => 'docs','action'=>'users', 'page' => 'notes'), null, TRUE); ?>" rel="facebox" title="Add Project">
			<?php echo $this->InteractIcon('help', 'About User Notes');?>
			<div class="action_text">Help</div>
		</a>
	</div>		
</div>
<?php 
	$options = array('notes' => $this->notes);
	echo $this->partial('pm/notes/partials/notes', $options); 
endif;
?>


<?php if($this->bookmarks):?>
<div class="content_headers">
	<div class="bookmark_header">Bookmarks</div>	
	<div class="actions">
		<a href="<?php echo $this->url('pm', array('module' => 'pm','controller' => 'docs','action'=>'users', 'page' => 'bookmarks'), null, TRUE); ?>" rel="facebox" title="Add Project">
			<?php echo $this->InteractIcon('help', 'About User Bookmarks');?>
			<div class="action_text">Help</div>
		</a>
	</div>	
</div>
<?php 
	$options = array('bookmarks' => $this->bookmarks);
	echo $this->partial('pm/bookmarks/partials/bookmarks', $options); 
endif; ?>

<?php 
if($this->times):
?>
<div class="content_headers">
	<div class="timetracker_header">Timetracker</div>
	<div class="actions">
		<a href="<?php echo $this->url('pm', array('module' => 'pm','controller' => 'docs','action'=>'users', 'page' => 'times'), null, TRUE); ?>" rel="facebox" title="Add Project">
			<?php echo $this->InteractIcon('help', 'About User Times');?>
			<div class="action_text">Help</div>
		</a>
	</div>		
</div>
<?php 
	$options = array('times' => $this->times, 'enable_project' => 'yes', 'enable_task' => 'yes', 'enable_company' => 'yes', 'enable_date' => 'yes');
	echo $this->partial('pm/times/partials/times', $options); 
endif; ?>
