<table cellpadding="0" cellspacing="0" class="<?php echo ($this->tableclass) ? $this->tableclass : 'tablesorter'; ?>" id="<?php echo ($this->tableid) ? $this->tableid : 'moji_contacts'; ?>">
	<thead>
		<tr>
			<th>Name</th>
			<th>Email</th>
			<th>Phone</th>
			<th>Added</th>
			<th>Last Modified</th>
			<?php if($this->enable_actions):?>
			<th>Actions</th>
			<?php endif; ?>
		</tr>
	</thead>

	<tbody>
		<?php 
		$i = 0;
		foreach($this->contacts as $contact)
		{
		?>
		<tr>
			<td><a title="<?php echo $contact['first_name']; ?> <?php echo $contact['last_name']; ?>" <?php echo ($this->facebox == 'yes' ? 'rel="facebox"' : ''); ?> href="<?php echo $this->url('contacts/view', array('contact_id' => $contact['id'])); ?>"><?php echo $contact['first_name']; ?> <?php echo $contact['last_name']; ?></a></td>
			<td><a title="<?php echo $contact['email']; ?>" href="mailto:<?php echo $contact['email']; ?>"><?php echo $contact['email']; ?></a></td>
			<td><?php 
			if($contact['mobile'] != '')
			{
				echo $contact['mobile'];
			}
			elseif($contact['phone_home'] != '')
			{
				echo $contact['phone_home'];
			}
			elseif($contact['phone2'] != '')
			{
				echo $contact['phone2'];
			}			
			else
			{
				echo 'N/A';
			} 
			?></td>
			<td><?php echo $this->RelativeDate($contact['created_date']); ?></td>
			<td><?php echo $this->RelativeDate($contact['last_modified']); ?></td>
			<?php if($this->enable_actions):?>
			<td>
			<a href="<?php echo $this->url(array('module' => 'pm','controller'=>'contacts','action'=>'edit', 'id' => $contact['id']), null, TRUE); ?>" title="Edit"><?php echo $this->InteractIcon('pencil', 'Edit');?></a>
			<a <?php echo ($this->facebox == 'yes' ? 'rel="facebox"' : ''); ?> href="<?php echo $this->url(array('module' => 'pm','controller'=>'contacts','action'=>'remove', 'id' => $contact['id']), null, TRUE); ?>" title="Delete"><?php echo $this->InteractIcon('cross', 'Delete');?></a>
			</td>
			<?php endif; ?>
		</tr>
		<?php 
		}
		?>
	</tbody>
</table>