<div class="content_headers" style="padding-top:0px;">
	<div class="timetracker_header">Timetracker</div>
		<?php echo $this->ActionBlock('help', 'Help', $this->url(array('module' => 'pm','controller' => 'docs','action'=>'times', 'page' => 'main'), null, TRUE), 'facebox');?>	
		<?php echo $this->ActionBlock('chart', 'Report', $this->url(array('module' => 'pm','controller' => 'reports','action'=>'times', 'date' => $this->full_date), null, TRUE), 'facebox');?>
</div>
<?php

echo $this->Calendar(
						$this->calendar_data,
						$this->url(array('module' => 'pm','controller'=>'times','action'=>'view-day'), null, FALSE),
						'date',
						$this->month,
						$this->year,
						FALSE
					);