<div class="content_headers" style="padding-top:0px;">
	<div class="timetracker_header">Delete Time</div>	
</div>
<div class="attention png_bg">
Are you sure you want to remove <?php echo $this->time_data['hours']?> from 
<?php 
if(isset($this->time_data['task_name']))
{
	echo "the task ".$this->time_data['task_name'];
}
elseif(isset($this->time_data['project_name']))
{
	echo "the project ".$this->time_data['project_name'];
}
else
{
	echo "the company ".$this->time_data['company_name'];
}
?>
? This can not be undone...
</div>

<p>
<form action="<?php echo $this->url(array('module' => 'pm','controller'=>'times','action'=>'remove', 'id' => $this->time_data['id']), null, TRUE); ?>" method="POST">
	<input type="submit" class="submit" value="Yes" name="confirm" /> <input type="submit" class="submit" value="No" name="fail"/>
</form>
</p>