<div class="content_headers" style="padding-top:0px;">
	<div class="timetracker_header">Existing Time For <?php echo $this->RelativeDate(date('Y-m-d', mktime(0, 0, 0, $this->month, $this->day+1, $this->year))); ?></div>
	<?php echo $this->ActionBlock('help', 'Help', $this->url('pm', array('module' => 'pm','controller' => 'docs','action'=>'times', 'page' => 'view-day'), null, TRUE), 'facebox');?>	
</div>
<?php 
$next_day = date('j', mktime(0, 0, 0, $this->month, $this->day+1, $this->year));
$next_year = date('Y', mktime(0, 0, 0, $this->month, $this->day+1, $this->year));
$next_month = date('n', mktime(0, 0, 0, $this->month, $this->day+1, $this->year));

$prev_day = date('Y-m-d', mktime(0, 0, 0, $this->month, $this->day-1, $this->year));
?>
<div >
	<div class="left">
		<div class="back_link_content">
			<a href="<?php echo $this->url('times/view-day', array('month' => $this->month, 'day' => $this->day, 'year' => $this->year)); ?>" title="Back to <?php echo $this->user_data['first_name'].' '.$this->user_data['last_name']; ?>">
				<?php echo $this->RelativeDate($prev_day); ?>	
			</a><div><?php echo $this->InteractIcon('left-arrow', $this->RelativeDate($prev_day));?></div>
		</div>
	</div>
	<?php if($this->date < date('Y-m-d')):?> 	
	<div class="right">
		<div class="back_link_content">
			<a href="<?php echo $this->url('times/view-day', array('month' => $next_month, 'day' => $next_day, 'year' => $next_year)); ?>">
				<?php echo $this->RelativeDate($next_day); ?> 
			</a><div style="float:right; padding-left:5px;"><?php echo $this->InteractIcon('right-arrow', $this->RelativeDate($prev_day));?></div>
		</div>	
	</div>
	<?php endif; ?>
</div>
<?php 
if($this->times):
	$options = array('times' => $this->times, 'enable_actions' => 'yes', 'enable_company' => 'yes', 'enable_project' => 'yes', 'enable_task' => 'yes');
	//echo $this->partial('pm/times/partials/times', $options);

else: ?>
<br clear="all" />
<div class="information png_bg">There hasn't been any time added yet.</div>

<?php 
endif; 

$options = array('form' => $this->form, 'date' => $this->date);
//echo $this->partial('pm/times/partials/form', $options);
?>