<div class="content_headers" style="padding-top:0px;">
	<div class="timers_header">
	<?php if(isset($this->timer_data['task_id'])): ?>
	Task Timer For: <?php echo $this->timer_data['name']; ?>
	<?php elseif(isset($this->timer_data['project_id'])):?>
	Project Timer For: <?php echo $this->timer_data['name']; ?>	
	<?php elseif(isset($this->timer_data['company_id'])):?>
	Company Timer For: <?php echo $this->timer_data['name']; ?>	
	<?php else: ?>
	Timer
	<?php endif; ?>	
	</div>
		<div class="actions">
			<a href="<?php echo $this->url(array('module' => 'pm','controller' => 'timers','action'=>'remove'), null, TRUE); ?>" title="Delete">
				<?php echo $this->InteractIcon('cross', 'Delete');?>
				<div class="action_text">Delete</div>
			</a>
		</div>		
</div>

<?php 
$options = array('form' => $this->form, 'timer_data' => $this->timer_data);
echo $this->partial('timers/partials/form.phtml', $options); 
?>