<div class="content_headers" style="padding-top:0px;">
	<div class="file_version_header">Add File Revision: <?php echo $this->Truncate($this->file['name'], 30); ?></div>		
</div>
<?php 
$options = array('id' => $this->file['id'], 'controller' => 'files', 'name' => $this->file['name'], 'action' => 'view');
echo $this->BackToLink($options); 

$options = array('form' => $this->form);
echo $this->partial('files/partials/form-revision.phtml', $options); 
?>