<div class="content_headers" style="padding-top:0px;">
	<div class="file_header">Remove File: <?php echo $this->file['name']?></div>		
</div>
<?php 
$options = array('id' => $this->file['id'], 'controller' => 'files', 'name' => $this->file['name'], 'action' => 'view');
echo $this->BackToLink($options);
?>
<div class="attention png_bg">
Are you sure you want to remove "<?php echo $this->file['name']?>"? This can not be undone...
</div>

<p>
<form action="<?php echo $this->url(array('module' => 'pm','controller'=>'files','action'=>'remove', 'id' => $this->id), null, TRUE); ?>" method="POST">
	<input type="submit" class="submit" value="Yes" name="confirm" /> <input type="submit" class="submit" value="No" name="fail"/>
</form>
</p>