<div class="content_headers" style="padding-top:0px;">
	<div class="file_version_header">Remove File Revision: <?php echo $this->Truncate($this->file['file_name'], 30); ?></div>		
</div>
<?php 
$options = array('id' => $this->file_data['id'], 'controller' => 'files', 'name' => $this->file_data['name'], 'action' => 'view');
echo $this->BackToLink($options);

if($this->total_file_revisions > 1): ?>
<div class="attention png_bg">
Are you sure you want to remove "<?php echo $this->Truncate($this->file['file_name'], 30); ?>"? This can not be undone...
</div>

<p>
<form action="<?php echo $this->url(array('module' => 'pm','controller'=>'files','action'=>'remove-revision', 'id' => $this->id), null, TRUE); ?>" method="POST">
	<input type="submit" class="submit" value="Yes" name="confirm" /> <input type="submit" class="submit" value="No" name="fail"/>
</form>
</p>
<?php else: ?>
<div class="fail png_bg">
You can't remove the only revision of a file. Delete the entire file entry instead.
</div>
<?php
endif; 
?>