<style>
#loading
{
	display:none;
}
</style>
<form action="<?php echo $this->escape($this->form->getAction()); ?>" id="notes_form"
method="<?php echo $this->escape($this->form->getMethod()) ?>" enctype="<?php echo $this->escape($this->form->getEnctype()); ?>">
<input type="hidden" name="date_default" id="date_default" value="<?php echo date('Y-m-d'); ?>" />

<?php 
if($this->id > 0)
	echo '<input type="hidden" value="'.$this->id.'" name="id" />';
?>

	<p>
		<label for="subject">Subject</label>
		<?php echo $this->form->subject; ?>
	</p>
	
	<?php if($this->company): ?>
	<p>
		<label for="company_id" id="companies">Company</label>
		<a href="<?php echo $this->url(array('module' => 'pm','controller'=>'companies','action'=>'view', 'id' => $this->company['id']), null, TRUE); ?>"><?php echo $this->company['name']; ?></a>
		<input type="hidden" name="company" value="<?php echo $this->company['id']; ?>" />
	</p>
	<?php endif; ?>
	
	<?php if($this->project): ?>
	<p>
		<label for="project_id">Project</label>
		<a href="<?php echo $this->url(array('module' => 'pm','controller'=>'projects','action'=>'view', 'id' => $this->project['id']), null, TRUE); ?>"><?php echo $this->project['name']; ?></a>
		<input type="hidden" name="project" value="<?php echo $this->project['id']; ?>" />
	</p>
	<?php endif; ?>
	
	<?php if($this->task): ?>
	<p>
		<label for="task_id">Task</label>
		<a href="<?php echo $this->url(array('module' => 'pm','controller'=>'tasks','action'=>'view', 'id' => $this->task['id']), null, TRUE); ?>"><?php echo $this->task['name']; ?></a>
		<input type="hidden" name="task" value="<?php echo $this->task['id']; ?>" />
	</p>
	<?php endif; ?>
	
	<p>
		<label for="topic">Topic</label>
		<?php echo $this->form->topic; ?>
	</p>
	
	<p style="display:none;" id="date_topic">
		<label for="date">Date</label>
		<?php echo $this->form->date; ?> <?php echo $this->form->date_hour; ?> <?php echo $this->form->date_minute; ?>
	</p>	
		
	<p>
		<label for="description">Description</label>
		<?php echo $this->form->description; ?>
	</p>
	
	<p>
		<input type="submit" class="submit" value="Submit" />
	</p>		
				
</form>	

<div id="loading"><img src="/images/loading.gif" /></div>
<script type="text/javascript">
var def_topic = '<?php echo ($this->task_data['topic'] ? $this->task_data['topic'] : 0); ?>';
jQuery(document).ready(function($){


	$('#date').DatePicker({
		format:'Y-m-d',
		date: $('#date').val(),
		current: $('#date').val(),
		starts: 1,
		position: 'r',
		eventName: 'click',
		onBeforeShow: function(){
		var default_end_date = ($('#date').val() != '' ? $('#date').val() : $('#date_default').val())
			$('#date').DatePickerSetDate(default_end_date, true);
		},
		onChange: function(formated, dates){
			$('#date').val(formated);
			$('#date').DatePickerHide();
			
		}
	});	
		
	$("#topic").change(function(){
		//$("#assignment_comment").show();
		var new_topic = $("#topic").val();
		if(new_topic == def_topic || new_topic == 1)
		{
			//$("#date_topic").show();
		}
		else
		{
			$("#date_topic").hide();
		}
	});
		
	$("#notes_form").validate({
		rules: {
			subject: "required",
			description: "required"
		},
		messages: {
			subject: "Please enter a subject",
			description: "Please enter a description"			
		}
	});	
});
</script>	