<div class="content_headers" style="padding-top:0px;">
	<div class="file_version_header">Viewing File Revision: <?php echo $this->Truncate($this->rev_data['file_name'], 30); ?></div>		
</div>
<?php if(!$this->preview_exists): ?>
<div class="fail png_bg">
Preview doesn't exist...
</div>

<?php
return;
endif;
?>
<img src="<?php echo $this->url(array('module' => 'pm','controller'=>'files','action'=>'preview-revision', 'id' => $this->rev_data['id'], 'view-type' => 'html'), null, TRUE); ?>" />

<div class="content_headers">
	<div class="file_peer_reviews_header">Peer Reviews</div>
</div>
<?php 
if($this->file_reviews):
	$options = array('reviews' => $this->file_reviews);
	echo $this->partial('files/partials/reviews.phtml', $options); 
else: 
?>
<div class="information png_bg">There aren't any reviews yet. </div>
<?php 
endif;
?>