	<h1>Welcome to MojiTrac!</h1>		
<?php 
$form = $this->form;
$form->setAttribute('id', 'sumbitForm');
$form->prepare();

if(is_array($this->messages) && count($this->messages) >= 1)
{
	foreach($this->messages AS $message) 
	{
		echo '<div class="fail large png_bg">'.$message.'</div>';
	}
} else {
	
	echo '<div class="information large png_bg">To log in please enter your credentials below.</div> ';
}
?>		
		<?php echo $this->form()->openTag($form);; ?>
		<?php 
		$csrf = $form->get('_x');
		echo $this->formRow($csrf); ?>				  
		<p><label>Email</label>
		<?php 
		$email = $form->get('email');
		echo $this->formRow($email); ?>
	  </p>
		
	  <p><label>Password</label>
	  <?php 
	  $password = $form->get('password');
	  echo $this->formRow($password); ?>
	  </p>
	  
	  <p>
	  	<input type="submit" name="Submit" id="button" value="Login"  class="button"/>
		<input type="reset" name="reset" id="reset" value="Reset" class="button" />
		
		<br />
		<a href="<?php //echo $this->url(array('controller'=>'forgot-password','action'=>'index'));?>">Forgot Password</a>
	  </p>
		
	<?php echo $this->form()->closeTag() ?>
	
<script type="text/javascript">
$.validator.setDefaults({
	//submitHandler: function() { alert("submitted!"); }
});

$().ready(function() {

	$("#email").focus();
	$("#sumbitForm").validate({
		rules: {
			email: "required",
			password: "required"
		},
		messages: {
			email: "Please enter an email address",
			password: "Please enter a password"
		}
	});

});

</script>	