
<form action="<?php echo $this->escape($this->form->getAction()); ?>" id="form_settings" method="<?php echo $this->escape($this->form->getMethod()) ?>"> 

<div id="form_tabs">
	<ul>
		<li><a href="#general">General</a></li>
		<li><a href="#date_time">Date/Time</a></li>
		<li><a href="#files">Files</a></li>
	</ul>
	<div id="general">
		<p>
			<label for="master_company">Master Company</label>
			<?php echo $this->form->master_company; ?>
		</p>
		<p>
			<label for="enable_ip"><?php echo $this->form->enable_ip; ?> Enable Ip Locker</label>
		</p>
		<p>
			<input type="submit" class="submit" value="Submit" />
		</p>
	</div>
	
	<div id="date_time">
		<p>
			<label for="timezone">Global Timezone</label>
			<?php echo $this->form->timezone; ?>
		</p>
		
		<p>
			<label for="date_format">Date Format</label>
			<?php echo $this->form->date_format; ?>
		</p>	
		
		<p style="display: none" id="date_format_custom_p">
			<label for="date_format_customt">Custom Date Format</label>
			<?php echo $this->form->date_format_custom; ?> <a href="<?php echo $this->url(array('module' => 'pm','controller' => 'docs','action'=>'settings', 'page' => 'date_format'), null, TRUE); ?>" rel="facebox"><?php echo $this->InteractIcon('help', 'About Date Formats');?></a> 
		</p>			
		
		<p>
			<label for="time_format">Time Format</label>
			<?php echo $this->form->time_format; ?> 
		</p>
		
		<p style="display: none" id="time_format_custom_p">
			<label for="time_format_customt">Custom Time Format</label>
			<?php echo $this->form->time_format_custom; ?> <a href="<?php echo $this->url(array('module' => 'pm','controller' => 'docs','action'=>'settings', 'page' => 'time_format'), null, TRUE); ?>" rel="facebox"><?php echo $this->InteractIcon('help', 'About Time Formats');?></a> 
		</p>
		
		<p>
			<input type="submit" class="submit" value="Submit" />
		</p>	
	</div>
	
	<div id="files">
		<p>
			<label for="allowed_file_formats">Allowed File Formats <a href="<?php echo $this->url(array('module' => 'pm','controller' => 'docs','action'=>'settings', 'page' => 'allowed_file_formats'), null, TRUE); ?>" rel="facebox"><?php echo $this->InteractIcon('help', 'About Allowed File Formats');?></a></label>
			<?php echo $this->form->allowed_file_formats; ?>
		</p>
		<p>
			<input type="submit" class="submit" value="Submit" />
		</p>
	</div>	

</div>	

<script type="text/javascript">
jQuery(document).ready(function($){

	if($("#time_format").val() == 'custom')
	{
		$("#time_format_custom_p").show();
	}

	if($("#date_format").val() == 'custom')
	{
		$("#date_format_custom_p").show();
	}	
		
	$("#time_format").change(function(){
		//$("#assignment_comment").show();
		var time_format = $("#time_format").val();
		if(time_format == 'custom')
		{
			$("#time_format_custom_p").show();
		}
		else
		{
			$("#time_format_custom_p").hide();
		}
	});

	$("#date_format").change(function(){
		//$("#assignment_comment").show();
		var date_format = $("#date_format").val();
		if(date_format == 'custom')
		{
			$("#date_format_custom_p").show();
		}
		else
		{
			$("#date_format_custom_p").hide();
		}
	});	

	$.validator.addMethod( 'valDateFormatCustom', function(value,element) {
		if($("#date_format").val() == 'custom' && $("#date_format_custom").val() == '')
		{
			return false;
		}
		return true;
	});
	$.validator.addMethod( 'valTimeFormatCustom', function(value,element) {
		if($("#time_format").val() == 'custom' && $("#time_format_custom").val() == '')
		{
			return false;
		}
		return true;
	});
	
	$('#form_settings').validate({
			rules: {
				date_format_custom: 'valDateFormatCustom',
				time_format_custom: 'valTimeFormatCustom'
			},
			messages: {
				date_format_custom: "required",
				time_format_custom: "required"
			}
	});
		
});
</script>		
</form>	