<?php 
$form = $this->form;
$form->setAttribute('id', 'form_settings');
$form->prepare();
echo $this->form()->openTag($form);
$csrf = $form->get('_x');
echo $this->formRow($csrf);
?>
<div id="form_tabs">
	<ul>
		<li><a href="#general">General</a></li>
		<li><a href="#files">Files</a></li>
		<li><a href="#i18n">i18n</a></li>
	</ul>
	<div id="general">
		<p>
			<label for="master_company">Master Company</label>
			<?php $field = $form->get('master_company'); echo $this->formRow($field); ?>
		</p>
		<p>
			<label for="enable_ip"><?php $field = $form->get('enable_ip'); echo $this->formRow($field); ?> Enable Ip Locker</label>
		</p>
		<p>
			<input type="submit" class="submit" value="Submit" />
		</p>
	</div>
	
	<div id="files">
		<p>
			<label for="allowed_file_formats">Allowed File Formats <a href="<?php echo $this->url('docs', array('module' => 'pm','controller' => 'docs','action'=>'settings', 'page' => 'allowed_file_formats'), null, TRUE); ?>" rel="facebox"><?php echo $this->InteractIcon('help', 'About Allowed File Formats');?></a></label>
			<?php $field = $form->get('allowed_file_formats'); echo $this->formRow($field); ?>
		</p>
		<p>
			<input type="submit" class="submit" value="Submit" />
		</p>
	</div>
	
	<div id="i18n">
		<p>
			<label for="timezone">Timezone <a href="<?php echo $this->url('docs', array('module' => 'pm','controller' => 'docs','action'=>'settings', 'page' => 'allowed_file_formats'), null, TRUE); ?>" rel="facebox"><?php echo $this->InteractIcon('help', 'About Allowed File Formats');?></a></label>
			<?php $field = $form->get('timezone'); echo $this->formRow($field); ?>
		</p>
		<p>
			<label for="locale">Locale <a href="<?php echo $this->url('docs', array('module' => 'pm','controller' => 'docs','action'=>'settings', 'page' => 'allowed_file_formats'), null, TRUE); ?>" rel="facebox"><?php echo $this->InteractIcon('help', 'About Allowed File Formats');?></a></label>
			<?php $field = $form->get('locale'); echo $this->formRow($field); ?>
		</p>		
		<p>
			<input type="submit" class="submit" value="Submit" />
		</p>
	</div>		

</div>	

<script type="text/javascript">
jQuery(document).ready(function($){

	if($("#time_format").val() == 'custom')
	{
		$("#time_format_custom_p").show();
	}

	if($("#date_format").val() == 'custom')
	{
		$("#date_format_custom_p").show();
	}	
		
	$("#time_format").change(function(){
		//$("#assignment_comment").show();
		var time_format = $("#time_format").val();
		if(time_format == 'custom')
		{
			$("#time_format_custom_p").show();
		}
		else
		{
			$("#time_format_custom_p").hide();
		}
	});

	$("#date_format").change(function(){
		//$("#assignment_comment").show();
		var date_format = $("#date_format").val();
		if(date_format == 'custom')
		{
			$("#date_format_custom_p").show();
		}
		else
		{
			$("#date_format_custom_p").hide();
		}
	});	

	$.validator.addMethod( 'valDateFormatCustom', function(value,element) {
		if($("#date_format").val() == 'custom' && $("#date_format_custom").val() == '')
		{
			return false;
		}
		return true;
	});
	$.validator.addMethod( 'valTimeFormatCustom', function(value,element) {
		if($("#time_format").val() == 'custom' && $("#time_format_custom").val() == '')
		{
			return false;
		}
		return true;
	});
	
	$('#form_settings').validate({
			rules: {
				date_format_custom: 'valDateFormatCustom',
				time_format_custom: 'valTimeFormatCustom'
			},
			messages: {
				date_format_custom: "required",
				time_format_custom: "required"
			}
	});
		
});
</script>		
<?php echo $this->ConfirmPageUnload('#form_settings')?>
<?php echo $this->form()->closeTag() ?>