<div class="content_headers" style="padding-top:0px;">
	<div class="calendar_header">Calendar</div>
		<div class="actions">
			<a href="<?php echo $this->url('docs', array('module' => 'pm','controller' => 'docs','action'=>'calendar', 'page' => 'main'), null, TRUE); ?>" rel="facebox" title="About Calendar">
				<?php echo $this->InteractIcon('help', 'About Calendar');?>
				<div class="action_text">Help</div>
			</a>
		</div>	
</div>
<?php
$calendar_data = array();
foreach($this->calendar_data AS $date => $data)
{
	$count = 0;
	foreach($data AS $item)
	{
		$calendar_data[$date][$count] = $item;
		if($item['type'] == 'projects')
		{
			$calendar_data[$date][$count]['string'] = '<img src="/images/icons/database_32.png" height="12" /> '.$calendar_data[$date][$count]['string'];
		}
		$count++;
	}
}

echo $this->Calendar($this->month, $this->year)
		  ->setData($calendar_data)
		  ->setItemLinkBase('calendar/view-day')
		  ->setDateLinkBase('calendar/month')
		  ->getCalendarHtml(			
			array(
				'showToday'=>TRUE, 
				'showPrevMonthLink'=>TRUE, 
				'showNextMonthLink'=>TRUE, 
				'tableClass'=>"calendar", 
				'selectBox'=>TRUE, 
				'selectBoxName'=>"date", 
				'selectBoxFormName'=>"selectMonthForm"
			)
);