<div class="content_headers" style="padding-top:0px;">
	<div class="calendar_header">Project Activity For <?php echo $this->RelativeDate($this->date); ?></div>
	<div class="actions">
		<a href="<?php echo $this->url(array('module' => 'pm','controller' => 'docs','action'=>'calendar', 'page' => 'view-day'), null, TRUE); ?>" rel="facebox" title="Add Project">
			<?php echo $this->InteractIcon('help', 'About Calendar Day View');?>
			<div class="action_text">Help</div>
		</a>
	</div>	
</div>
<?php 
$parts = explode('-', $this->date);
$next_day = date('Y-m-d', mktime(0, 0, 0, $parts['1'], $parts['2']+1, $parts['0']));
$prev_day = date('Y-m-d', mktime(0, 0, 0, $parts['1'], $parts['2']-1, $parts['0']));
?>
<div >
	<div class="left">
		<div class="back_link_content">
			<a href="<?php echo $this->url(array('module' => 'pm','controller'=>'calendar','action'=>'view-day', 'date'=>$prev_day), null, TRUE); ?>" title="Back to <?php echo $this->user_data['first_name'].' '.$this->user_data['last_name']; ?>">
				<?php echo $this->RelativeDate($prev_day); ?>	
			</a><div><?php echo $this->InteractIcon('left-arrow', $this->RelativeDate($prev_day));?></div>
		</div>
	</div>
	<div class="right">
		<div class="back_link_content">
			<a href="<?php echo $this->url(array('module' => 'pm','controller'=>'calendar','action'=>'view-day', 'date'=>$next_day)); ?>">
				<?php echo $this->RelativeDate($next_day); ?> 
			</a><div style="float:right; padding-left:5px;"><?php echo $this->InteractIcon('right-arrow', $this->RelativeDate($prev_day));?></div>
		</div>	
	</div>
</div>

<?php 
if($this->project_data):
	$options = array('projects' => $this->project_data, 'enable_company' => 'yes');
	echo $this->partial('projects/partials/projects.phtml', $options);

else: ?>
<br clear="all" />
<div class="information png_bg">There aren't any projects for this date.</div>

<?php 
endif; 
?>
<div class="content_headers" style="padding-top:0px;">
	<div class="task_header">Tasks</div>
</div>
<?php 
if($this->task_data):
	$options = array('tasks' => $this->task_data, 'enable_project' => 'yes', 'enable_assigned' => 'yes', 'enable_completion' => 'yes', 'enable_due' => 'yes', 'enable_start' => 'yes');
	echo $this->partial('tasks/partials/tasks.phtml', $options);

else: ?>
<br clear="all" />
<div class="information png_bg">There aren't any tasks for this date.</div>

<?php 
endif; 
?>