<div class="content_headers" style="padding-top:0px;">
	<div class="note_header">Remove Note: <?php echo $this->note['subject']?></div>		
</div>
<?php if(!$this->ajax_mode): 
?>
<div class="back_link_content">
	<?php if($this->note['task_name']): ?>
	<a href="<?php echo $this->url(array('module' => 'pm','controller'=>'tasks','action'=>'view', 'id' => $this->note['task_id']), null, TRUE); ?>" title="Back to <?php echo $this->task['name']; ?>">
		Back to <?php echo $this->note['task_name']; ?>
	</a>
	<?php elseif($this->note['project_name']): ?>
	<a href="<?php echo $this->url(array('module' => 'pm','controller'=>'projects','action'=>'view', 'id' => $this->note['project_id']), null, TRUE); ?>" title="Back to <?php echo $this->note['project_name']; ?>">
		Back to <?php echo $this->note['project_name']; ?>
	</a>	
	<?php else: ?>
	<a href="<?php echo $this->url(array('module' => 'pm','controller'=>'companies','action'=>'view'), null, TRUE); ?>" title="Back to <?php echo $this->note['company_name']; ?>">
		Back to <?php echo $this->note['company_name']; ?>
	</a>	
	<?php endif; ?>
	<div><?php echo $this->InteractIcon('left-arrow', 'Back');?></div>
	
</div>	
<br clear="all" />
<?php endif; ?>
<div class="attention png_bg">
Are you sure you want to remove "<?php echo $this->note['subject']?>"? This can not be undone...
</div>

<p>
<form action="<?php echo $this->url(array('module' => 'pm','controller'=>'notes','action'=>'remove', 'id' => $this->id), null, TRUE); ?>" method="POST">
	<input type="submit" class="submit" value="Yes" name="confirm" /> <input type="submit" class="submit" value="No" name="fail"/>
</form>
</p>