<div class="content_headers" style="padding-top:0px;">
	<div class="project_header">Edit Project</div>	
</div>
<div class="back_link_content">
	<a href="<?php echo $this->url(array('module' => 'pm','controller'=>'projects','action'=>'view', 'id'=>$this->project_data['id']), null, TRUE); ?>" title="Back to <?php echo $this->company_data['name']; ?>">
		Back to <?php echo $this->project_data['name']; ?>	
	</a><div><?php echo $this->InteractIcon('left-arrow', 'Back to '.$this->project_data['name']);?></div>
</div>
<br clear="all" />
<?php 
$options = array('form' => $this->form, 'id' => $this->id);
echo $this->partial('projects/partials/form.phtml', $options); 
?>