<div class="content_headers" style="padding-top:0px;">
	<div class="project_header">Delete Project: <?php echo $this->project['name']?></div>	
</div>
<div class="attention png_bg">
Are you sure you want to remove "<?php echo $this->project['name']?>"? This can not be undone...
</div>

<p>
<form action="<?php echo $this->url('projects/remove', array('project_id' => $this->id), null, TRUE); ?>" method="POST">
	<input type="submit" class="submit" value="Yes" name="confirm" /> <input type="submit" class="submit" value="No" name="fail"/>
</form>
</p>

<h2>Project Details</h2>
<p>
<?php echo $this->project['name']?> contains:
<br />
<?php echo $this->task_count; ?> Tasks<br />
<?php echo $this->file_count; ?> Files

</p>