<div class="content_headers" style="padding-top:0px;">
	<div class="user_role_header">Invite User</div>	
</div>
<p>
<?php 
$form = $this->form;
$form->setAttribute('action', $this->url('users/invite'));
$form->prepare();
echo $this->form()->openTag($form);
$csrf = $form->get('_x');
echo $this->formRow($csrf);
?>
<style>
#loading
{
	display:none;
}
</style>
<div id="oputput"></div>
<p>
	<label for="email">Email</label>
	<?php $name = $form->get('email'); echo $this->formRow($name); ?>
</p>

<p class="user_role_boxes"><br /><label for="">Assigned Roles:</label>
	<?php $field = $form->get('user_roles'); echo $this->formRow($field); ?>		
</p>

<p>
	<input type="submit" class="submit" value="Submit" />
</p>
<?php echo $this->ConfirmPageUnload('#invite_form')?>
<?php echo $this->form()->closeTag() ?>
</p>
<script type="text/javascript">
jQuery(document).ready(function($){

	$("#invite_form").validate({
		rules: {
			email: {
				required: true,
				email: true
			},
		},
		messages: {
			email: {
				required: "Please enter an email",
				email: "Please enter a valid email address"
			},			
		}
	});	
});
</script>