<h1>Forgot Password</h1>		
<?php 

$form = $this->form;
$form->setAttribute('id', 'sumbitForm');
$form->prepare();

if(is_array($this->messages) && count($this->messages) >= 1)
{
	foreach($this->messages AS $message) 
	{
		echo '<div class="fail large png_bg">'.$message.'</div>';
	}
} else {
	
	echo '<div class="information large png_bg">Welcome. To log in enter your credentials below.</div> ';
}

echo $this->form()->openTag($form); 
		$csrf = $form->get('_x');
		echo $this->formRow($csrf); ?>				  
		<p><label>Email</label>
		<?php 
		$email = $form->get('email');
		echo $this->formRow($email); ?>		
	  </p>
	  
	  <p><input type="submit" name="Submit" id="button" value="Submit"  class="button"/></p>
		<a href="<?php echo $this->url('login');?>" class="blueLink">Back to Login</a>
<?php echo $this->form()->closeTag() ?>
	
<script type="text/javascript">
$.validator.setDefaults({
	//submitHandler: function() { alert("submitted!"); }
});

$().ready(function() {

	$("#email").focus();
	$("#sumbitForm").validate({
		rules: {
			email: "required"
		},
		messages: {
			email: "Please enter an email address"
		}
	});

});

</script>