	<h1>Forgot Password</h1>		
<?php 

if(is_array($this->messages) && count($this->messages) >= 1)
{
	foreach($this->messages AS $message) 
	{
		echo '<div class="fail large png_bg">'.$message.'</div>';
	}
} else {
	
	echo '<div class="information large png_bg">Welcome. To log in enter your credentials below.</div> ';
}
?>		
			<form action="<?php echo $this->escape($this->form->getAction()); ?>" 
				  method="<?php echo $this->escape($this->form->getMethod()) ?>" 
				  id="sumbitForm">
				  
		<p><label>Email</label>
		<?php echo $this->form->email; ?>
	  </p>
	  
	  <p><input type="submit" name="Submit" id="button" value="Submit"  class="button"/></p>
		<a href="<?php echo $this->url(array('controller'=>'login','action'=>'index'));?>" class="blueLink">Back to Login</a>
	</form>
	
<script type="text/javascript">
$.validator.setDefaults({
	//submitHandler: function() { alert("submitted!"); }
});

$().ready(function() {

	$("#email").focus();
	$("#sumbitForm").validate({
		rules: {
			email: "required"
		},
		messages: {
			email: "Please enter an email address"
		}
	});

});

</script>