<div class="content_headers" style="padding-top:0px;">
	<div class="task_header">Add Task</div>	
</div>
<?php if($this->project_data['id']): ?>
<div class="back_link_content">
	<a href="<?php echo $this->url(array('module' => 'pm','controller'=>'projects','action'=>'view', 'id'=>$this->project_data['id']), null, TRUE); ?>" title="Back to <?php echo $this->project_data['name']; ?>">
		Back to <?php echo $this->project_data['name']; ?>	
	</a><div><?php echo $this->InteractIcon('left-arrow', 'Back to '.$this->project_data['name']);?></div>
</div>
<br clear="all" />
<?php endif;?>
<?php 
$options = array('form' => $this->form, 'project_data' => $this->project_data, 'company_data' => $this->company_data);
echo $this->partial('tasks/partials/form.phtml', $options); 
?>