<div class="content_headers" style="padding-top:0px;">
	<div class="task_header">Edit Task</div>	
</div>
<div class="back_link_content">
	<a href="<?php echo $this->url(array('module' => 'pm','controller'=>'tasks','action'=>'view', 'id'=>$this->task_data['id']), null, TRUE); ?>" title="Back to <?php echo $this->task_data['name']; ?>">
		Back to <?php echo $this->task_data['name']; ?>	
	</a><div><?php echo $this->InteractIcon('left-arrow', 'Back to '.$this->task_data['name']);?></div>
</div>
<br clear="all" />
<?php 
$options = array('form' => $this->form, 'id' => $this->id, 'project_data' => $this->project_data, 'task_data' => $this->task_data);
echo $this->partial('tasks/partials/form.phtml', $options); 
?>