<div class="content_headers" style="padding-top:0px;">

	<div class="company_header"><?php echo $this->company['name']; ?></div>
		<div class="actions">
			<a href="<?php echo $this->url(array('module' => 'pm','controller' => 'docs','action'=>'companies', 'page' => 'view'), null, TRUE); ?>" rel="facebox" title="Add Companies">
				<?php echo $this->InteractIcon('help', 'About Companies');?>
				<div class="action_text">Help</div>
			</a>
		</div>		
		
		<?php if($this->company['state'] || $this->company['address1'] || $this->company['city'] || $this->company['zip']):?>
		<div class="actions">
			<a href="<?php echo $this->url(array('module' => 'pm','controller'=>'companies','action'=>'map'), null, FALSE); ?>" rel="facebox" title="Map">
				<?php echo $this->InteractIcon('map', 'Map');?> 
				<div class="action_text">Map</div>
			</a>
		</div>
		<?php endif; ?>

		<?php if($this->company['primary_url']): ?>
		<div class="actions">
			<a href="<?php echo $this->company['primary_url']; ?>" target="_blank" title="Website"> 
				<?php echo $this->InteractIcon('www', 'Company Website');?> 
				<div class="action_text">Website</div>
			</a>
		</div>
		<?php endif; ?>
		
		<?php if($this->CheckPermission('track_time')):?>
		<div class="actions">
			<a href="<?php echo $this->url(array('module' => 'pm','controller' => 'timers','action'=>'view', 'company' => $this->id), null, TRUE); ?>" title="Timer" rel="facebox">
				<?php echo $this->InteractIcon('timer', 'Timer');?>
				<div class="action_text">Timer</div>
			</a>
		</div>	
		<?php endif; ?>	
				
		<?php if($this->CheckPermission('manage_companies')):?>
		<div class="actions">
			<a href="<?php echo $this->url(array('module' => 'pm','controller'=>'companies','action'=>'remove'), null, FALSE); ?>" title="Delete" rel="facebox">
				<?php echo $this->InteractIcon('cross', 'Delete Company');?>
				<div class="action_text">Delete</div>
			</a>
		</div>		
		<div class="actions">
			<a href="<?php echo $this->url(array('module' => 'pm','controller'=>'companies','action'=>'edit'), null, FALSE); ?>" title="Edit">
				<?php echo $this->InteractIcon('pencil', 'Edit Company');?>
				<div class="action_text">Edit</div>
			</a> 
		</div>
		<?php endif; ?>		
</div>

<?php echo $this->Breadcrumb('company', $this->id); ?>
<div class="item_details">
    <div class="items">
    	<p>
			<span class="bold">Type:</span> <?php echo $this->CompanyType($this->company['type']); ?><br />
			<span class="bold">Modified:</span> <?php echo $this->RelativeDate($this->company['last_modified']); ?><br />
			<span class="bold">Created:</span> <?php echo $this->RelativeDate($this->company['created_date']); ?><br />
			<?php if($this->company['type'] == '6'):?>
			<span class="bold">Hours:</span> <?php echo number_format($this->hours['total'], 2); ?><br />
			<?php endif; ?>
    	</p>
    </div>
    <?php if($this->company['state'] || $this->company['address1'] || $this->company['city'] || $this->company['zip']):?>
    <div class="items" style="padding-left:10px;">
    	<p>
    		<?php if($this->company['address1']):?>
				<span class="bold">Address 1:</span> <?php echo $this->company['address1']; ?><br />
			<?php endif; ?> 
			<?php if($this->company['address2']):?>
				<span class="bold">Address 2:</span> <?php echo $this->company['address2']; ?><br />
			<?php endif; ?> 
			<?php if($this->company['city']):?>
				<span class="bold">City:</span> <?php echo $this->company['city']; ?><br />
			<?php endif; ?> 
			<?php if($this->company['state']):?>
				<span class="bold">State:</span> <?php echo $this->company['state']; ?><br />
			<?php endif; ?> 
			<?php if($this->company['zip']):?>
				<span class="bold">Zip:</span> <?php echo $this->company['zip']; ?>
			<?php endif; ?> 
    	</p>
    </div>
    <?php endif; ?>
    <?php if($this->company['phone1'] || $this->company['phone2'] || $this->company['fax']):?>
    <div class="items" style="padding-left:10px;">
    	<p>
			<?php if($this->company['phone1']):?>
				<span class="bold">Phone 1:</span> <?php echo $this->company['phone1']; ?><br />
			<?php endif; ?>
			<?php if($this->company['phone2']):?>
				<span class="bold">Phone 2:</span> <?php echo $this->company['phone2']; ?><br />
			<?php endif; ?>
			<?php if($this->company['fax']):?>
				<span class="bold">Fax:</span> <?php echo $this->company['fax']; ?>  
			<?php endif; ?>  	
    	</p>
    </div>
    <?php endif; ?>
    <?php if($this->CheckPermission('view_time') && $this->company['type'] == '1'): ?>
    <div class="items" style="padding-left:10px;">
		<?php 
			$options = array('hours' => $this->hours, 'type' => 'company', 'id' => $this->id);
			echo $this->partial('times/partials/hour_status.phtml', $options); 		
		?>
    </div>
    <?php endif; ?>
</div>

<br clear="all" />

<?php if($this->company['description'] != ''): ?>
	<h2>Description:</h2>
	<p>
	<?php echo $this->FormatHtml($this->company['description']); ?>      	
	</p>
<?php endif; ?>

<?php if($this->CheckPermission('view_projects') && ($this->company['type'] == '1' || $this->company['type'] == '6')): ?>
	<div class="content_headers">
		<div class="project_header">Projects</div>
		<?php if($this->CheckPermission('manage_projects')): ?>
		<div class="actions">
			<a href="<?php echo $this->url(array('module' => 'pm','controller' => 'docs','action'=>'companies', 'page' => 'projects'), null, TRUE); ?>" rel="facebox" title="About Company Projects">
				<?php echo $this->InteractIcon('help', 'About Company Projects');?>
				<div class="action_text">Help</div>
			</a>
		</div>		
		<div class="actions">
			<a href="<?php echo $this->url(array('module' => 'pm','controller'=>'projects','action'=>'index', 'company' => $this->id), null, TRUE); ?>" title="View All">
				<?php echo $this->InteractIcon('view-all', 'View All Company Projects');?> 
				<div class="action_text">View All</div>
			</a>
		</div>
		
		<div class="actions">
			<a href="<?php echo $this->url(array('module' => 'pm','controller'=>'projects','action'=>'add', 'company' => $this->id), null, TRUE); ?>" title="Add Project">
				<?php echo $this->InteractIcon('add', 'Add Project');?>
				<div class="action_text">Add Project</div>
			</a>
		</div>
		
		<?php endif; ?>
	</div>
	<?php 
	if($this->projects):
		$options = array('projects' => $this->projects);
		echo $this->partial('projects/partials/projects.phtml', $options); 
	else: 
	?>
	<div class="information png_bg">There aren't any projects added yet. Want to <a href="<?php echo $this->url(array('module' => 'pm','controller'=>'projects','action'=>'add', 'company' => $this->id), null, TRUE); ?>">add</a> one?</div>
	<?php endif; ?>
<?php endif; ?>

<!-- 
<?php if($this->CheckPermission('view_invoices') && ($this->company['type'] == '1' || $this->company['type'] == '6')): ?>
	<div class="content_headers">
		<div class="invoice_header">Invoices</div>
		<div class="actions">
			<a href="<?php echo $this->url(array('module' => 'pm','controller' => 'docs','action'=>'invoices', 'page' => 'contacts'), null, TRUE); ?>" rel="facebox" title="About Company Invoice">
				<?php echo $this->InteractIcon('help', 'About Company Invoices');?>
				<div class="action_text">Help</div>
			</a>
		</div>			
		<div class="actions">
			<a href="<?php echo $this->url(array('module' => 'pm','controller'=>'invoices','action'=>'index', 'company' => $this->id), null, TRUE); ?>" title="View All">
				<?php echo $this->InteractIcon('view-all', 'View All Company Invoices');?> 
				<div class="action_text">View All</div>
			</a>
		</div>			
		<?php if($this->CheckPermission('manage_company_contacts')): ?>	
		<div class="actions">
			<a href="<?php echo $this->url(array('module' => 'pm','controller'=>'invoices','action'=>'add', 'company' => $this->id), null, TRUE); ?>" title="Add Invoice">
				<?php echo $this->InteractIcon('add', 'Add Company Invoice');?>
				<div class="action_text">Add Invoice</div>
			</a>
		</div>
		<?php endif; ?>
	</div>
	<?php 
	if($this->contacts):
		$options = array('contacts' => $this->contacts, 'facebox' => 'yes');
		echo $this->partial('contacts/partials/contacts.phtml', $options); 
	else: 
	?>
	<div class="information png_bg">
		There aren't any contacts added yet. 
		<?php if($this->CheckPermission('manage_company_contacts')): ?>
			Want to <a href="<?php echo $this->url(array('module' => 'pm','controller'=>'contacts','action'=>'add', 'company' => $this->id), null, TRUE); ?>">add</a> one?
		<?php endif; ?>
	</div>
	<?php 
	endif;
endif; ?>
 -->
<?php 
if($this->CheckPermission('view_company_contacts')):?>
	<div class="content_headers">
		<div class="contact_header">Contacts</div>
		<div class="actions">
			<a href="<?php echo $this->url(array('module' => 'pm','controller' => 'docs','action'=>'companies', 'page' => 'contacts'), null, TRUE); ?>" rel="facebox" title="About Company Contacts">
				<?php echo $this->InteractIcon('help', 'About Company Contacts');?>
				<div class="action_text">Help</div>
			</a>
		</div>			
		<div class="actions">
			<a href="<?php echo $this->url(array('module' => 'pm','controller'=>'contacts','action'=>'index', 'company' => $this->id), null, TRUE); ?>" title="View All">
				<?php echo $this->InteractIcon('view-all', 'View All Company Contacts');?> 
				<div class="action_text">View All</div>
			</a>
		</div>			
		<?php if($this->CheckPermission('manage_company_contacts')): ?>	
		<div class="actions">
			<a href="<?php echo $this->url(array('module' => 'pm','controller'=>'contacts','action'=>'add', 'company' => $this->id), null, TRUE); ?>" title="Add Contact">
				<?php echo $this->InteractIcon('add', 'Add Company Contact');?>
				<div class="action_text">Add Contact</div>
			</a>
		</div>
		<?php endif; ?>
	</div>
	<?php 
	if($this->contacts):
		$options = array('contacts' => $this->contacts, 'facebox' => 'yes');
		echo $this->partial('contacts/partials/contacts.phtml', $options); 
	else: 
	?>
	<div class="information png_bg">
		There aren't any contacts added yet. 
		<?php if($this->CheckPermission('manage_company_contacts')): ?>
			Want to <a href="<?php echo $this->url(array('module' => 'pm','controller'=>'contacts','action'=>'add', 'company' => $this->id), null, TRUE); ?>">add</a> one?
		<?php endif; ?>
	</div>
	<?php 
	endif;
endif;
	?>

<div class="content_headers">
	<div class="file_header">Files</div>
		<div class="actions">
			<a href="<?php echo $this->url(array('module' => 'pm','controller' => 'docs','action'=>'companies', 'page' => 'files'), null, TRUE); ?>" rel="facebox" title="About Company Files">
				<?php echo $this->InteractIcon('help', 'About Company Files');?>
				<div class="action_text">Help</div>
			</a>
		</div>		
		<div class="actions">
			<a href="<?php echo $this->url(array('module' => 'pm','controller'=>'files','action'=>'index', 'company' => $this->id), null, TRUE); ?>" title="View All">
				<?php echo $this->InteractIcon('view-all', 'View All Company Files');?> 
				<div class="action_text">View All</div>
			</a>
		</div>		
	<div class="actions">
		<a href="<?php echo $this->url(array('module' => 'pm','controller'=>'files','action'=>'add', 'company' => $this->id), null, TRUE); ?>" rel="facebox" title="Add File">
			<?php echo $this->InteractIcon('add', 'Add Company File');?>
			<div class="action_text">Add File</div>
		</a>
	</div>
</div>
<?php 
if($this->files):
	$options = array('files' => $this->files, 'enable_project' => 'yes', 'enable_task' => 'yes');
	echo $this->partial('files/partials/files.phtml', $options); 
else: 
?>
<div class="information png_bg">There aren't any files added yet. Want to <a href="<?php echo $this->url(array('module' => 'pm','controller'=>'files','action'=>'add', 'company' => $this->id), null, TRUE); ?>">add</a> one?</div>
<?php 
endif;
?>

<div class="content_headers">
	<div class="note_header">Notes</div>
	<div class="actions">
		<a href="<?php echo $this->url(array('module' => 'pm','controller' => 'docs','action'=>'companies', 'page' => 'notes'), null, TRUE); ?>" rel="facebox" title="About Company Notes">
			<?php echo $this->InteractIcon('help', 'About Company Notes');?>
			<div class="action_text">Help</div>
		</a>
	</div>		
	<div class="actions">
		<a href="<?php echo $this->url(array('module' => 'pm','controller'=>'notes','action'=>'index', 'company' => $this->id), null, TRUE); ?>" title="View All">
			<?php echo $this->InteractIcon('view-all', 'View All Company Notes');?>
			<div class="action_text">View All</div>
		</a>
	</div>		
	<div class="actions">
		<a rel="facebox" href="<?php echo $this->url(array('module' => 'pm','controller'=>'notes','action'=>'add', 'company' => $this->id), null, TRUE); ?>" title="Add Note">
			<?php echo $this->InteractIcon('add', 'Add Company Note');?>
			<div class="action_text">Add Note</div>
		</a>
	</div>
</div>
<?php 
if($this->notes):
	$options = array('notes' => $this->notes, 'facebox' => 'yes', 'enable_project' => 'yes', 'enable_task' => 'yes');
	echo $this->partial('notes/partials/notes.phtml', $options); 
else: 
?>
<div class="information png_bg">There aren't any notes added yet. Want to <a href="<?php echo $this->url(array('module' => 'pm','controller'=>'notes','action'=>'add', 'company' => $this->id), null, TRUE); ?>">add</a> one?</div>
<?php 
endif;
?>

<div class="content_headers">
	<div class="bookmark_header">Bookmarks</div>
	<div class="actions">
		<a href="<?php echo $this->url(array('module' => 'pm','controller' => 'docs','action'=>'companies', 'page' => 'bookmarks'), null, TRUE); ?>" rel="facebox" title="About Company Bookmarks">
			<?php echo $this->InteractIcon('help', 'About Company Bookmarks');?>
			<div class="action_text">Help</div>
		</a>
	</div>		
	<div class="actions">
		<a href="<?php echo $this->url(array('module' => 'pm','controller'=>'bookmarks','action'=>'index', 'company' => $this->id), null, TRUE); ?>" title="View All">
			<?php echo $this->InteractIcon('view-all', 'View All Company Bookmarks');?> 
			<div class="action_text">View All</div>
		</a>
	</div>	
	<div class="actions">
		<a rel="facebox" href="<?php echo $this->url(array('module' => 'pm','controller'=>'bookmarks','action'=>'add', 'company' => $this->id), null, TRUE); ?>" title="Add Bookmark">
			<?php echo $this->InteractIcon('add', 'Add Company Bookmark');?>
			<div class="action_text">Add Bookmark</div>
		</a>
	</div>
</div>
<?php if($this->bookmarks):
	$options = array('bookmarks' => $this->bookmarks, 'facebox' => 'yes', 'enable_project' => 'yes', 'enable_task' => 'yes');
	echo $this->partial('bookmarks/partials/bookmarks.phtml', $options); 
else: 
?>
<div class="information png_bg">There aren't any bookmarks added yet. Want to <a href="<?php echo $this->url(array('module' => 'pm','controller'=>'bookmarks','action'=>'add', 'company' => $this->id), null, TRUE); ?>">add</a> one?</div>
<?php endif; ?>

<?php if($this->company['type'] == '1' || $this->company['type'] == '6'): ?>

	<div class="content_headers">
		<div class="timetracker_header">Timetracker</div>
		<div class="actions">
			<a href="<?php echo $this->url(array('module' => 'pm','controller' => 'docs','action'=>'companies', 'page' => 'times'), null, TRUE); ?>" rel="facebox" title="About Company Times">
				<?php echo $this->InteractIcon('help', 'About Company Times');?>
				<div class="action_text">Help</div>
			</a>
		</div>			
		<div class="actions">
			<a href="<?php echo $this->url(array('module' => 'pm','controller'=>'times','action'=>'view', 'company' => $this->id), null, TRUE); ?>" title="View All">
				<?php echo $this->InteractIcon('view-all', 'View All Company Time');?>
				<div class="action_text">View All</div>
			</a>
		</div>
	</div>
	<?php 
	if($this->times):
		$options = array('times' => $this->times, 'enable_project' => 'yes', 'enable_task' => 'yes', 'enable_date' => 'yes');
		echo $this->partial('times/partials/times.phtml', $options); 
	else: 
	?>
	<div class="information png_bg">There aren't any times added yet.</div>
	<?php endif; ?>
<?php endif; ?>
