
<form action="<?php echo $this->escape($this->form->getAction()); ?>" 
method="<?php echo $this->escape($this->form->getMethod()) ?>"> 
<?php 
if($this->id > 0)
	echo '<input type="hidden" value="'.$this->id.'" name="id" />';
?>
	
		<p>
			<label for="name">Title</label>
			<?php echo $this->form->name; ?>
		</p>
		<p>
			<label for="area">Area</label>
			<?php echo $this->form->area; ?>
		</p>
		
		<p>
			<input type="submit" class="submit" value="Submit" />
		</p>			
</form>	