<div class="content_headers" style="padding-top:0px;">
	<div class="admin_header">Remove Option</div>	
</div>
<?php if(!$this->ajax_mode): ?>
<div class="back_link_content">
	<a href="<?php echo $this->url(array('module' => 'pm','controller'=>'options','action'=>'view', 'id'=>$this->id), null, TRUE); ?>" title="Back to Option">
		Back to Options
	</a><div><?php echo $this->InteractIcon('left-arrow', 'Back to Options');?></div>
</div>	
<br clear="all" />
<?php endif; ?>

<div class="attention png_bg">
Are you sure you want to remove the Option "<?php echo $this->option['name']?>"? This can not be undone...
</div>
<p>
<form action="<?php echo $this->url(array('module' => 'pm','controller'=>'options','action'=>'remove', 'id' => $this->id), null, TRUE); ?>" method="POST">
	<input type="submit" class="submit" value="Yes" name="confirm" /> <input type="submit" class="submit" value="No" name="fail"/>
</form>
</p>
