<div class="content_headers" style="padding-top:0px;">
	<div class="user_role_header">Remove User Role</div>	
</div>

<?php if($this->deny_remove): ?>
<div class="fail png_bg">You can't remove this role.</div>
<?php else: ?>

<div class="attention png_bg">
Are you sure you want to remove the "<?php echo $this->role['name']?>" role? This can not be undone...
</div>
<p>
<form action="" method="POST">
	<input type="submit" class="submit" value="Yes" name="confirm" /> <input type="submit" class="submit" value="No" name="fail"/>
</form>
</p>

<?php endif; ?>